function [datesNum,waterLevels] = import_boewrt_fun(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [datesNum,waterLevels] = import_boewrt_fun(FILENAME) Reads
%   data from text file FILENAME for the default selection.
%
%   [datesNum,waterLevels] = import_boewrt_fun(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [datesNum,waterLevels] = import_boewrt_fun('DK_Aarhus_01Jan2006-31Dez2006_10.min_nAE_NN.boe.dat',13, 51841);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/10/19 14:03:15

%% Initialize variables.
delimiter = {',',';'};
if nargin<=3
    endRow = inf;
end

%% Format string for each line of text:
%   column1: datetimes (%{dd.MM.yyyy HH:mm:ss}D)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{dd.MM.yyyy HH:mm:ss}D%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.


%% Allocate imported array to column variable names
datesNum = datenum(dataArray{:, 1});
waterLevels = dataArray{:, 2};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% CNUMMERDESFEUCHTENPUNKTESI10=datenum(CNUMMERDESFEUCHTENPUNKTESI10);


